### ISSUE TITLE
Add a visible "Test Data" note to all embeds

### ISSUE THREAD

**Issue by alykat** [nprapps/elections20-primaries#10]
Maybe a text label positioned in the background?

We'll need it especially once we start distributing these to stations. (B/c AP will still be running tests all next week and on Iowa day.)

Will need to have an easy way to turn OFF the flag, too. Or maybe it looks for a test-data flag in the JSON, and once we switch from test AP data to live AP data, the "test data" label on the graphic disappears.

**Comment by thomaswilburn** [comment]
There should be a test flag in the data that we can use (since we may have files in the bucket in various stages of test-hood once the primaries are under way). I'll add a banner tomorrow.
