### ISSUE TITLE
Governor results detail page doesn't show the statewide results table if no party is specified

### ISSUE THREAD

**Issue by alykat** [nprapps/elections20-primaries#105]
Washington State had an open/mixed primary for its governor's race.

The overall result table appears here:
https://apps.npr.org/elections20-primaries/states/WA.html#date=8%2F4%2F2020&office=G

But not on the detail page with county-level results:
https://apps.npr.org/elections20-primaries/states/WA.html#counties=true&date=8%2F4%2F2020&party=undefined&office=G

**Comment by thomaswilburn** [comment]
It's a problem with party being set to "undefined" on the widget, so the filter is bad (if you unset the party attribute, it works just fine). I thought I had fixed that, but maybe I did it for one of the other race types.

**Comment by thomaswilburn** [comment]
Fixed in 731d4bf
