### ISSUE TITLE
When results are in, the top candidates shown should be the top vote-getters

### ISSUE THREAD

**Issue by alykat** [nprapps/elections20-primaries#13]
Right now for Iowa, I see:

Collapsed: The six candidates we chose to display by default when no results are in

Open: All candidates with data — including a several who (in the test data) have more votes than some of our placeholder candidates.

**Comment by thomaswilburn** [comment]
I believe this is an issue with the test API, which is currently delivering data that doesn't actually sort the same way between "votes" (such as they are) and SDEs. There's no way to sort between the two consistently until they sort that out, or we have real data.

**Comment by thomaswilburn** [comment]
Oh no, sorry, I misunderstood! Yes, this is a bug.
