### ISSUE TITLE
Delegate at-a-glance widget

### ISSUE THREAD

**Issue by thomaswilburn** [nprapps/elections20-primaries#20]
Shows the top three candidates and links to the delegate tracker.
![image](https://user-images.githubusercontent.com/881329/73007623-d5f52880-3dda-11ea-9770-17bfdb32ebe1.png)

**Comment by alykat** [comment]
Writing out what we discussed: Since we don't have data (even test data) in the delegate feed for now (and also probably won't have a delegate tracker to link to), it may be best to build this from a manually-edited sheet in the config spreadsheet. We can revisit in the lead-up to NH.

**Comment by alykat** [comment]
Note: 1,991 delegates are needed for the nomination, counter to what the comp says

**Comment by alykat** [comment]
Punting to NH

**Comment by thomaswilburn** [comment]
This may not be completely done, but the majority of work was finished in a632b8dae46eafbbae7cf1d2269c00072e0fa282
