### ISSUE TITLE
The title on the results table should be configurable from the spreadsheet or have some kind of smarter default

### ISSUE THREAD

**Issue by alykat** [nprapps/elections20-primaries#31]
currently hard-coded

https://github.com/nprapps/elections20-primaries/blob/master/src/js/components/iowa-widget/_outer.html#L2

**Comment by thomaswilburn** [comment]
I'll add this as a column tomorrow, and we can probably even move it out of the widget and into the surrounding page. I imagine we'll need to do this for other races as well.
