### ISSUE TITLE
DC coming in as "undefined" in calendar and on state page

### ISSUE THREAD

**Issue by alykat** [nprapps/elections20-primaries#63]
![image](https://user-images.githubusercontent.com/491318/75396758-4f44d700-58c3-11ea-9611-33268a489a9f.png)

![image](https://user-images.githubusercontent.com/491318/75396769-54098b00-58c3-11ea-9980-73c16f6a60c4.png)

**Comment by thomaswilburn** [comment]
Fixed in the sheet.
