### ISSUE TITLE
Calendar: Results links shouldn't be clickable until they're available

### ISSUE THREAD

**Issue by alykat** [nprapps/elections20-primaries#65]
Noted by Audrey. Behavior should match the calendars on top of the state pages?

**Comment by alykat** [comment]
Thanks!

I think I like the idea of including the references to what races are up on a given day, just not linking them. So something like this: (top one: previous races that have results; bottom one: races on a future date)

![image](https://user-images.githubusercontent.com/491318/75410247-3c44fd80-58e9-11ea-9a01-18850ad9e97b.png)

I can take care of the blue links with CSS. Now trying to figure out what to do about that "results" lead-in text...

**Comment by thomaswilburn** [comment]
If you swap the code that's commented out in calender.js, there should already be CSS checked in, and you'd just need to add a class for hiding the label text.
