### ISSUE TITLE
"See County Results" links should be grouped under the relevant results table

### ISSUE THREAD

**Issue by alykat** [nprapps/elections20-primaries#73]
Right now the links are at the top of the page

Example: http://stage-apps.npr.org/elections20-primaries/states/NC.html?eternal

![image](https://user-images.githubusercontent.com/491318/75415035-67831900-58f8-11ea-8eb5-37d0ec7a4063.png)

**Comment by thomaswilburn** [comment]
Audrey and I talked about this, and I think she's going to tackle it. Working plan:

* The data elements (`president-primary`, `president-caucus`, `standard-primary`) should have an optional `host` attribute
* If the host is set to "state-page" (or whatever flag value we choose) we alter the behavior of how it sets up the child result tables:
  * Change the headline to be less repetitive
  * Set the href of the result table to point toward the hash link of the county table
  * Any other cosmetic changes that might make sense
