### ISSUE TITLE
Don't treat candidates whose opponents got zero votes as uncontested

### ISSUE THREAD

**Issue by audreycarlsen** [nprapps/elections20-primaries#85]
On some races, for some data (NC-Gov-R was the example), it seems that it may be possible for a candidate to have zero votes in that county so they get folded into other. This is weird when there's only two candidates in the contest anyway. We've temporarily fixed this with 8ea7b77, but we should verify this to make sure the solution doesn't create weirdness in another location.

**Comment by thomaswilburn** [comment]
I think this looks reasonable, but we'll revisit.
