### ISSUE TITLE
AR Senate only has a GOP primary?

### ISSUE THREAD

**Issue by alykat** [nprapps/elections20-primaries#87]
And an uncontested one at that. But we're showing links to both Dem and GOP primaries.

/states/AR.html?eternal#date=3%2F3%2F2020&office=S

![image](https://user-images.githubusercontent.com/491318/75596382-58b67680-5a5e-11ea-9131-4261010c25c6.png)

**Comment by thomaswilburn** [comment]
Fixing in the sheet.
